### ISSUE TITLE
src_url in nexus/settings.sls only points to "archived" packages, not latest.

### ISSUE THREAD

**Issue by ds-rakhbari** [saltstack-formulas/nexus-formula#6]
src_url http://www.sonatype.org/downloads/ in nexus/settings.sls only points to "archived" packages, not latest. 

If you want let's say ver 3.x.x, it's a different location URL:
https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.0-03-unix.tar.gz

I know I can set source_url in my pillar or grains, but that should show up in pillar.example and it doesn't.

Also in settings.sls...
`{%- set source_url = g.get('source_url', p.get('source-url',`

Why is grains param name "source_url" and the pillar param name "source-url"? Underscore vs. hyphon? Just a typo? It's inconsistent.

**Comment by sroegner** [comment]
@ds-rakhbari would you mind packing all the fixes into a PR? You seem in a good position to do some testing ...

**Comment by arthurlogilab** [comment]
+1

**Comment by philippkahr** [comment]
not relevant, since pillar contains full url for version 3
